name: Build and deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-publish-on-master:
    runs-on: ubuntu-latest
    steps:

      - name: Sjekk ut koden
        uses: actions/checkout@v3

      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: '17.x'

      - name: Bygg og kjør tester
        run: ./gradlew build
